### ISSUE TITLE
Web links in the book

### ISSUE THREAD

**Issue by opiruyan** [jezhumble/cdsite#6]
Hello

In the corresponding paragraph you say there are two ways to go the link: either with bit.ly or continuousdelivery.com/go.

While the first option works the second seems not to.
So 
http://continuousdelivery.com/go/bibNp0 
result in 404.

**Comment by nepito** [comment]
Some similar in [here](https://github.com/jezhumble/cdsite/blob/d27e6d33d64ec6391d8446deba1651c02c5e6a9d/_pages/implementing/patterns.md?plain=1#L11C76-L11C76):
 > Our goal was to make deployment to any environment a fully automated, scripted process that could be performed on demand in minutes (on the original project [we got it down to less than an hour](http://dizzythinks.net/the-first-bluegreen-production-deployment-circa-2005.html), which was a big deal for an enterprise system in 2005).

result in 403: `Code: AccessDenied`

**Comment by jezhumble** [comment]
Unfortunately this feature is no longer supported.
